#!/usr/bin/python

tcp_options = {
#type,length,value,description
	'0':['1','',"End of option list"],
	'1':['1','',"No operation"],
	'2':['4','',"MSS"],
	'3':['3','',"Window scale factor"],
	'4':['2','',"SACK permitted"],
	'5':['n','',"SACK"],
	'6':['6','',"Echo"],
	'7':['6','',"Echo reply"],
	'8':['10','',"Timestamp"],
	'9':['2','',"Partial order connection permitted"],
	'10',['3','',"Partial order service profile"],
	'11',['6','',"Connection count"],
	'12',['6','',"CC new"],
	'13',['6','',"CC echo"],
	'14',['3','',"Alternate checksum request"],
	'15',['n','',"Alternate checksum data"],
	'16',['','',"Skeeter"],
	'17',['','',"Bubba"],
	'18',['3','',"Trailer checksum option"],
	'19',['18','',"MD5 signature"],
	'20',['','',"SCPS capabilities"],
	'21',['','',"Selective negative acknowledgements"],
	'22',['','',"Record boundaries"],
	'23',['','',"Corruption experienced"],
	'24',['','',"SNAP"],
	'26',['','',"TCP compression filter"],
	'27',['8','',"Quick start filter"],
	'28',['4','',"User timeout"],
	'29',['','',"TCP-AO"],
	'30',['','',"MPTCP"],
	'38',['','',"WX 38"],
	'39',['','',"WX 39"],
	'253',['','',"RFC3692 experiment 1"],
	'254',['','',"RFC3692 experiment 2"],
}
